# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, inputs, ... }:

{
  imports = [
    inputs.disko.nixosModules.disko
    (import ./disko.nix { disks = [ "/dev/xvda" ]; })
  ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "sr_mod" "xen_blkfront" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  #fileSystems."/" =
  #  {
  #    device = "none";
  #    fsType = "tmpfs";
  #    options = [ "defaults" "size=2G" "mode=755" ];
  #  };
  #fileSystems."/nix" =
  #  {
  #    device = "/dev/disk/by-label/NIXNIX";
  #    fsType = "ext4";
  #  };

  #fileSystems."/boot" =
  #  {
  #    device = "/dev/disk/by-label/NIXBOOT";
  #    fsType = "vfat";
  #  };
  #

  # checkout the example folder for how to configure different disko layouts

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enX0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
