keys:
  - &admin c5cd97e60f8f93e7b6e7309d8ef5908be01ec60c
  - &system_nixos01 age1ua5syascg44cznulxh7jyqddwf079yqkngp9jyawn3rafdsfuy7slnay3y
  - &system_nixos02 age10gcmdw04ecc7q9qxhavfcns2rure4tsvvhc5cqwwghh6985e443sk7n25w
  - &system_aragog age1ra4pt3rkhulz675w938gm37j0w2tnnx889lgh0e8uepv8nuppexqs62dqm

creation_rules:
  - path_regex: default.sops.yaml$
    key_groups:
      - pgp:
        - *admin
        age:
          - *system_nixos01
          - *system_nixos02
          - *system_aragog
  - path_regex: acme.sops.yaml$
    key_groups:
      - pgp:
        - *admin
        age:
          - *system_nixos02
